export const AUTH_CONSTANTS = {
  MINIMUM_PASSWORD_LENGTH: 8,
  MAXIMUM_PASSWORD_LENGTH: 128,
  BCRYPT_SALT_ROUNDS: 12,
  ACCESS_TOKEN_TYPE: "Bearer",
  AUTHORIZATION_HEADER: "authorization"
} as const;